# Generated by Django 4.0.6 on 2022-09-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_captchastore_id_alter_captchastore_csrf_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchastore',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='captchastore',
            name='csrf_token',
            field=models.CharField(max_length=100),
        ),
    ]
