# Generated by Django 4.0.6 on 2022-12-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_captchastore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gravatar_email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.TextField(blank=True),
        ),
    ]
