# Generated by Django 5.2.1 on 2025-05-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
                ('spotify_uri', models.CharField(max_length=255, unique=True)),
                ('album_art_url', models.URLField(max_length=255)),
                ('custom_album_art', models.URLField(blank=True, max_length=255, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('explicit', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Song Metadata',
                'verbose_name_plural': 'Song Metadata',
            },
        ),
    ]
