# Generated by Django 5.2.1 on 2025-05-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmetadata',
            name='streaming_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
