# Generated by Django 5.2.1 on 2025-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_announcement_announcementtranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
