# Generated by Django 5.2.11 on 2026-03-11 19:06

import thatcomputerscientist.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_announcement_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(storage=thatcomputerscientist.storage.MinioStorage, upload_to='emojis/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'emojis',
                'ordering': ['name'],
            },
        ),
    ]
