# Generated by Django 4.0.6 on 2022-09-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_captchastore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captchastore',
            name='id',
        ),
        migrations.AlterField(
            model_name='captchastore',
            name='csrf_token',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
