# Generated by Django 4.0.6 on 2022-09-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_captchastore_id_alter_captchastore_csrf_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptchaStore',
        ),
    ]
