# Generated by Django 4.1.4 on 2022-12-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_userprofile_gravatar_email_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CaptchaStore",
        ),
    ]
