# Generated by Django 4.1.4 on 2023-05-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_tokenstore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenstore",
            name="expires",
            field=models.DateTimeField(),
        ),
    ]
