# Generated by Django 5.0.7 on 2024-12-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_tokenstore_expires"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="balance",
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
