# Generated by Django 5.0.7 on 2024-12-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_userprofile_balance_userprofile_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="journal_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="journal_streak_best",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="journal_streak_reset",
            field=models.BooleanField(default=False),
        ),
    ]
