# Generated by Django 4.0.6 on 2022-11-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='data',
            field=models.TextField(),
        ),
    ]
