# Generated by Django 4.0.6 on 2022-11-22 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_post_image'),
        ('ignis', '0002_alter_object_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectdirectory',
            name='name',
        ),
        migrations.AddField(
            model_name='objectdirectory',
            name='slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
            preserve_default=False,
        ),
    ]
