# Generated by Django 4.0.6 on 2022-11-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignis', '0003_remove_objectdirectory_name_objectdirectory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectdirectory',
            name='slug',
        ),
        migrations.AddField(
            model_name='objectdirectory',
            name='name',
            field=models.CharField(default='root', max_length=255),
        ),
    ]
