# Generated by Django 4.0.6 on 2022-11-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignis', '0004_remove_objectdirectory_slug_objectdirectory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectdirectory',
            name='name',
        ),
        migrations.AddField(
            model_name='objectdirectory',
            name='post_slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
