# Generated by Django 4.0.6 on 2022-11-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ignis', '0005_remove_objectdirectory_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectdirectory',
            old_name='post_slug',
            new_name='name',
        ),
    ]
