# Generated by Django 4.0.6 on 2022-11-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignis', '0006_rename_post_slug_objectdirectory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ignis.objectdirectory'),
        ),
    ]
