# Generated by Django 4.0.6 on 2022-11-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_post_image'),
        ('ignis', '0007_alter_object_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images//post_images')),
                ('temp_post_id', models.CharField(default=None, max_length=12, null=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images//repository_images')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images//repository_titles')),
            ],
        ),
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.DeleteModel(
            name='ObjectDirectory',
        ),
        migrations.AddField(
            model_name='repositoryimages',
            name='repository',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ignis.repositorytitles'),
        ),
    ]
