# Generated by Django 4.0.6 on 2022-11-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ignis', '0008_postimage_repositoryimages_repositorytitles_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepositoryTitles',
            new_name='RepositoryTitle',
        ),
        migrations.DeleteModel(
            name='RepositoryImages',
        ),
    ]
