# Generated by Django 4.0.6 on 2022-11-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignis', '0010_alter_postimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
