# Generated by Django 4.1.4 on 2022-12-31 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_post_post_image"),
        ("ignis", "0011_postimage_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images//cover_images")),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.post",
                    ),
                ),
            ],
        ),
    ]
