# Generated by Django 6.0.5 on 2026-07-04 17:28

import core.letters.models
import django.db.models.deletion
import thatcomputerscientist.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_letterattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Letter', 'verbose_name_plural': 'Letters'},
        ),
        migrations.AlterModelOptions(
            name='letterattachment',
            options={'ordering': ['created_at'], 'verbose_name': 'Letter Attachment', 'verbose_name_plural': 'Letter Attachments'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participant_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_one', to=settings.AUTH_USER_MODEL, verbose_name='Participant One'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participant_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_two', to=settings.AUTH_USER_MODEL, verbose_name='Participant Two'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='core.conversation', verbose_name='Conversation'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_letters', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='letterattachment',
            name='content_type',
            field=models.CharField(max_length=128, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='letterattachment',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conversation', verbose_name='Conversation'),
        ),
        migrations.AlterField(
            model_name='letterattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='letterattachment',
            name='file',
            field=models.FileField(storage=thatcomputerscientist.storage.MinioStorage, upload_to=core.letters.models._attachment_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='letterattachment',
            name='file_size',
            field=models.PositiveIntegerField(verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='letterattachment',
            name='letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.letter', verbose_name='Letter'),
        ),
        migrations.AlterField(
            model_name='letterattachment',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='Original Name'),
        ),
        migrations.AlterField(
            model_name='letterattachment',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
    ]
