# Generated by Django 5.2.11 on 2026-03-14 12:16

import django.db.models.deletion
import services.journals.models
import thatcomputerscientist.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_journalentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='cover_image',
            field=models.ImageField(blank=True, storage=thatcomputerscientist.storage.MinioStorage, upload_to=services.journals.models._journal_cover_path),
        ),
        migrations.AddField(
            model_name='journal',
            name='genre',
            field=models.CharField(blank=True, choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Sci-Fi'), ('romance', 'Romance'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('thriller', 'Thriller'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('slice_of_life', 'Slice of Life'), ('action', 'Action'), ('adventure', 'Adventure'), ('historical', 'Historical'), ('isekai', 'Isekai'), ('mecha', 'Mecha'), ('supernatural', 'Supernatural'), ('psychological', 'Psychological'), ('tragedy', 'Tragedy'), ('ecchi', 'Ecchi'), ('harem', 'Harem'), ('mahou_shoujo', 'Mahou Shoujo'), ('cyberpunk', 'Cyberpunk'), ('dystopian', 'Dystopian'), ('noir', 'Noir'), ('satire', 'Satire')], max_length=30),
        ),
        migrations.AddField(
            model_name='journal',
            name='mode',
            field=models.CharField(choices=[('default', 'Default'), ('book', 'Book'), ('light_novel', 'Light Novel'), ('short_stories', 'Short Stories'), ('diary', 'Diary'), ('poetry', 'Poetry')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('hiatus', 'Hiatus')], default='ongoing', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='form',
            field=models.CharField(blank=True, choices=[('free_verse', 'Free Verse'), ('haiku', 'Haiku'), ('tanka', 'Tanka'), ('sonnet', 'Sonnet'), ('limerick', 'Limerick'), ('ballad', 'Ballad'), ('ode', 'Ode'), ('elegy', 'Elegy'), ('ghazal', 'Ghazal'), ('villanelle', 'Villanelle'), ('acrostic', 'Acrostic'), ('prose_poetry', 'Prose Poetry'), ('concrete', 'Concrete'), ('renga', 'Renga'), ('spoken_word', 'Spoken Word')], max_length=30),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='genre',
            field=models.CharField(blank=True, choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Sci-Fi'), ('romance', 'Romance'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('thriller', 'Thriller'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('slice_of_life', 'Slice of Life'), ('action', 'Action'), ('adventure', 'Adventure'), ('historical', 'Historical'), ('isekai', 'Isekai'), ('mecha', 'Mecha'), ('supernatural', 'Supernatural'), ('psychological', 'Psychological'), ('tragedy', 'Tragedy'), ('ecchi', 'Ecchi'), ('harem', 'Harem'), ('mahou_shoujo', 'Mahou Shoujo'), ('cyberpunk', 'Cyberpunk'), ('dystopian', 'Dystopian'), ('noir', 'Noir'), ('satire', 'Satire')], max_length=30),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('angry', 'Angry'), ('grateful', 'Grateful'), ('tired', 'Tired'), ('excited', 'Excited'), ('reflective', 'Reflective'), ('nostalgic', 'Nostalgic'), ('hopeful', 'Hopeful'), ('stressed', 'Stressed'), ('content', 'Content'), ('lonely', 'Lonely'), ('inspired', 'Inspired'), ('melancholic', 'Melancholic'), ('peaceful', 'Peaceful'), ('frustrated', 'Frustrated'), ('numb', 'Numb'), ('curious', 'Curious')], max_length=30),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='thumbnail',
            field=models.ImageField(blank=True, storage=thatcomputerscientist.storage.MinioStorage, upload_to=services.journals.models._entry_thumbnail_path),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tone',
            field=models.CharField(blank=True, choices=[('dark', 'Dark'), ('light', 'Light'), ('comedic', 'Comedic'), ('serious', 'Serious'), ('melancholic', 'Melancholic'), ('whimsical', 'Whimsical'), ('gritty', 'Gritty'), ('surreal', 'Surreal'), ('wholesome', 'Wholesome'), ('bittersweet', 'Bittersweet'), ('absurdist', 'Absurdist'), ('noir', 'Noir'), ('dreamy', 'Dreamy'), ('tense', 'Tense')], max_length=30),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, storage=thatcomputerscientist.storage.MinioStorage, upload_to=services.journals.models._character_image_path)),
                ('bio', models.TextField(blank=True)),
                ('role', models.CharField(default='Supporting', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='services.journal')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tags', to='services.journal')),
            ],
            options={
                'unique_together': {('journal', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='services.entrytag'),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, storage=thatcomputerscientist.storage.MinioStorage, upload_to=services.journals.models._volume_cover_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='services.journal')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('journal', 'order')},
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='services.volume'),
        ),
        migrations.CreateModel(
            name='CharacterAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='services.character')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_appearances', to='services.journalentry')),
            ],
            options={
                'unique_together': {('character', 'entry')},
            },
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('from_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='services.character')),
                ('to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='services.character')),
            ],
            options={
                'unique_together': {('from_character', 'to_character')},
            },
        ),
    ]
