# Generated by Django 5.2.11 on 2026-03-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_journal_cover_image_journal_genre_journal_mode_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together=set(),
        ),
    ]
