# Generated by Django 6.0.5 on 2026-07-04 16:35

import django.db.models.deletion
import services.journals.models
import thatcomputerscientist.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_copy_weblog_data_from_blog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['order'], 'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='characterappearance',
            options={'verbose_name': 'Character Appearance', 'verbose_name_plural': 'Character Appearances'},
        ),
        migrations.AlterModelOptions(
            name='characterrelationship',
            options={'verbose_name': 'Character Relationship', 'verbose_name_plural': 'Character Relationships'},
        ),
        migrations.AlterModelOptions(
            name='entrytag',
            options={'verbose_name': 'Entry Tag', 'verbose_name_plural': 'Entry Tags'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Journal', 'verbose_name_plural': 'Journals'},
        ),
        migrations.AlterModelOptions(
            name='journalentrytranslation',
            options={'verbose_name': 'Journal Entry Translation', 'verbose_name_plural': 'Journal Entry Translations'},
        ),
        migrations.AlterModelOptions(
            name='journaltranslation',
            options={'verbose_name': 'Journal Translation', 'verbose_name_plural': 'Journal Translations'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['order'], 'verbose_name': 'Volume', 'verbose_name_plural': 'Volumes'},
        ),
        migrations.AlterField(
            model_name='character',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, storage=thatcomputerscientist.storage.MinioStorage, upload_to=services.journals.models._character_image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='character',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='services.journal', verbose_name='Journal'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='characterappearance',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='services.character', verbose_name='Character'),
        ),
        migrations.AlterField(
            model_name='characterappearance',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_appearances', to='services.journalentry', verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='characterappearance',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='characterrelationship',
            name='from_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='services.character', verbose_name='From Character'),
        ),
        migrations.AlterField(
            model_name='characterrelationship',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='characterrelationship',
            name='to_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='services.character', verbose_name='To Character'),
        ),
        migrations.AlterField(
            model_name='entrytag',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tags', to='services.journal', verbose_name='Journal'),
        ),
        migrations.AlterField(
            model_name='entrytag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='entrytag',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='cover_image',
            field=models.ImageField(blank=True, storage=thatcomputerscientist.storage.MinioStorage, upload_to=services.journals.models._journal_cover_path, verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='custom_css',
            field=models.TextField(blank=True, verbose_name='Custom CSS'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='genre',
            field=models.CharField(blank=True, choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Sci-Fi'), ('romance', 'Romance'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('thriller', 'Thriller'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('slice_of_life', 'Slice of Life'), ('action', 'Action'), ('adventure', 'Adventure'), ('historical', 'Historical'), ('isekai', 'Isekai'), ('mecha', 'Mecha'), ('supernatural', 'Supernatural'), ('psychological', 'Psychological'), ('tragedy', 'Tragedy'), ('ecchi', 'Ecchi'), ('harem', 'Harem'), ('mahou_shoujo', 'Mahou Shoujo'), ('cyberpunk', 'Cyberpunk'), ('dystopian', 'Dystopian'), ('noir', 'Noir'), ('satire', 'Satire')], max_length=30, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='mode',
            field=models.CharField(choices=[('default', 'Default'), ('book', 'Book'), ('light_novel', 'Light Novel'), ('short_stories', 'Short Stories'), ('diary', 'Diary'), ('poetry', 'Poetry')], default='default', max_length=20, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_journals', to=settings.AUTH_USER_MODEL, verbose_name='Shared With'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('hiatus', 'Hiatus')], default='ongoing', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entry Date'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='form',
            field=models.CharField(blank=True, choices=[('free_verse', 'Free Verse'), ('haiku', 'Haiku'), ('tanka', 'Tanka'), ('sonnet', 'Sonnet'), ('limerick', 'Limerick'), ('ballad', 'Ballad'), ('ode', 'Ode'), ('elegy', 'Elegy'), ('ghazal', 'Ghazal'), ('villanelle', 'Villanelle'), ('acrostic', 'Acrostic'), ('prose_poetry', 'Prose Poetry'), ('concrete', 'Concrete'), ('renga', 'Renga'), ('spoken_word', 'Spoken Word')], max_length=30, verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='genre',
            field=models.CharField(blank=True, choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Sci-Fi'), ('romance', 'Romance'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('thriller', 'Thriller'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('slice_of_life', 'Slice of Life'), ('action', 'Action'), ('adventure', 'Adventure'), ('historical', 'Historical'), ('isekai', 'Isekai'), ('mecha', 'Mecha'), ('supernatural', 'Supernatural'), ('psychological', 'Psychological'), ('tragedy', 'Tragedy'), ('ecchi', 'Ecchi'), ('harem', 'Harem'), ('mahou_shoujo', 'Mahou Shoujo'), ('cyberpunk', 'Cyberpunk'), ('dystopian', 'Dystopian'), ('noir', 'Noir'), ('satire', 'Satire')], max_length=30, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Draft'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='services.journal', verbose_name='Journal'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('angry', 'Angry'), ('grateful', 'Grateful'), ('tired', 'Tired'), ('excited', 'Excited'), ('reflective', 'Reflective'), ('nostalgic', 'Nostalgic'), ('hopeful', 'Hopeful'), ('stressed', 'Stressed'), ('content', 'Content'), ('lonely', 'Lonely'), ('inspired', 'Inspired'), ('melancholic', 'Melancholic'), ('peaceful', 'Peaceful'), ('frustrated', 'Frustrated'), ('numb', 'Numb'), ('curious', 'Curious')], max_length=30, verbose_name='Mood'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='services.entrytag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='thumbnail',
            field=models.ImageField(blank=True, storage=thatcomputerscientist.storage.MinioStorage, upload_to=services.journals.models._entry_thumbnail_path, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='tone',
            field=models.CharField(blank=True, choices=[('dark', 'Dark'), ('light', 'Light'), ('comedic', 'Comedic'), ('serious', 'Serious'), ('melancholic', 'Melancholic'), ('whimsical', 'Whimsical'), ('gritty', 'Gritty'), ('surreal', 'Surreal'), ('wholesome', 'Wholesome'), ('bittersweet', 'Bittersweet'), ('absurdist', 'Absurdist'), ('noir', 'Noir'), ('dreamy', 'Dreamy'), ('tense', 'Tense')], max_length=30, verbose_name='Tone'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='services.volume', verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='word_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Word Count'),
        ),
        migrations.AlterField(
            model_name='journalentrytranslation',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='journalentrytranslation',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.journalentry', verbose_name='Journal Entry'),
        ),
        migrations.AlterField(
            model_name='journalentrytranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='journaltranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='journaltranslation',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.journal', verbose_name='Journal'),
        ),
        migrations.AlterField(
            model_name='journaltranslation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='cover_image',
            field=models.ImageField(blank=True, storage=thatcomputerscientist.storage.MinioStorage, upload_to=services.journals.models._volume_cover_path, verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='services.journal', verbose_name='Journal'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
