# Generated by Django 4.1.4 on 2022-12-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(blank=True, upload_to="images/post-covers"),
        ),
    ]
