# Generated by Django 4.1.4 on 2022-12-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="post_image",
        ),
    ]
