# Generated by Django 4.1.4 on 2023-01-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.ImageField(blank=True, upload_to="images//cover_images"),
        ),
    ]
