# Generated by Django 5.0.7 on 2024-12-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_anonymouscommentuser_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
