# Generated by Django 5.0.7 on 2024-12-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_post_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body_ja",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_ja",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
