# Generated by Django 5.0.7 on 2024-12-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_post_body_ja_post_title_ja"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_ja",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
