# Generated by Django 5.0.7 on 2024-12-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_category_name_ja"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="name_ja",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
