# Generated by Django 5.1.4 on 2025-01-02 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_posttranslation_weblog_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weblog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.weblog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='weblog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.weblog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='weblog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.weblog'),
            preserve_default=False,
        ),
    ]
