# Generated by Django 5.2.1 on 2025-06-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
