# Generated by Django 5.2.1 on 2025-08-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_commentvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='anonymous_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_comments', to='blog.anonymouscommentuser'),
        ),
    ]
