# Generated by Django 5.2.1 on 2025-08-29 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20250829_0616'),
        ('blog', '0020_alter_comment_anonymous_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='anonymous_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.anonymouscommentuser'),
        ),
        migrations.DeleteModel(
            name='AnonymousCommentUser',
        ),
    ]
