# Generated by Django 5.2.1 on 2025-08-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_comment_anonymous_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentvote',
            options={'verbose_name': 'Comment Vote', 'verbose_name_plural': 'Comment Votes'},
        ),
    ]
