# Generated by Django 5.2.1 on 2025-09-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_commentvote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='spam_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='spam_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('spam', 'Marked as Spam')], db_index=True, default='pending', max_length=10),
        ),
    ]
