# Generated by Django 5.0.7 on 2024-12-16 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PagodaSites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField()),
                ("verified", models.BooleanField(default=False)),
                ("siteUniqueIdentifier", models.TextField(unique=True)),
                ("VerficationRecordName", models.CharField(blank=True, max_length=50)),
                (
                    "VerificationRecordValue",
                    models.CharField(blank=True, max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pagoda Sites",
                "ordering": ["-created_at"],
            },
        ),
    ]
