# Generated by Django 5.0.7 on 2024-12-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagoda", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagodasites",
            old_name="VerficationRecordName",
            new_name="verficationRecordName",
        ),
        migrations.RenameField(
            model_name="pagodasites",
            old_name="VerificationRecordValue",
            new_name="verificationRecordValue",
        ),
        migrations.AddField(
            model_name="pagodasites",
            name="verificationMethod",
            field=models.CharField(
                choices=[("DNS", "DNS"), ("Meta", "Meta")], default="DNS", max_length=4
            ),
        ),
    ]
