# Generated by Django 5.2.1 on 2025-08-29 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('email_public', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('blinkie_url', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_userprofile_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
