# Generated by Django 5.2.1 on 2025-08-29 05:55

from django.db import migrations


def copy_userprofile_data(apps, schema_editor):
    # Data migration was already completed before users app was deleted
    # This is now a no-op to avoid breaking migration history
    pass


def reverse_copy_userprofile_data(apps, schema_editor):
    # No-op reverse migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        # Removed users dependency since users app has been deleted
    ]

    operations = [
        migrations.RunPython(copy_userprofile_data, reverse_copy_userprofile_data),
    ]
