# Generated by Django 5.2.1 on 2025-08-29 06:16

from django.db import migrations


def copy_anonymouscommentuser_data(apps, schema_editor):
    # Get the model classes for both old and new AnonymousCommentUser
    OldAnonymousCommentUser = apps.get_model("blog", "AnonymousCommentUser")
    NewAnonymousCommentUser = apps.get_model("authentication", "AnonymousCommentUser")

    # Copy all data from old to new
    for old_user in OldAnonymousCommentUser.objects.all():
        NewAnonymousCommentUser.objects.create(
            id=old_user.id,  # Preserve the ID to maintain foreign key relationships
            name=old_user.name,
            email=old_user.email,
            token=old_user.token,
            avatar=old_user.avatar,
            created_at=old_user.created_at,
        )


def reverse_copy_anonymouscommentuser_data(apps, schema_editor):
    # This is for reversing the migration if needed
    NewAnonymousCommentUser = apps.get_model("authentication", "AnonymousCommentUser")
    NewAnonymousCommentUser.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_anonymouscommentuser_alter_userprofile_options"),
        (
            "blog",
            "0020_alter_comment_anonymous_user",
        ),  # Make sure blog migration has run
    ]

    operations = [
        migrations.RunPython(
            copy_anonymouscommentuser_data, reverse_copy_anonymouscommentuser_data
        ),
    ]
