# Generated by Django 6.0.5 on 2026-07-04 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20250829_0616'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymouscommentuser',
            options={'verbose_name': 'Anonymous User', 'verbose_name_plural': 'Anonymous Users'},
        ),
        migrations.AlterField(
            model_name='anonymouscommentuser',
            name='avatar',
            field=models.URLField(blank=True, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='anonymouscommentuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='anonymouscommentuser',
            name='email',
            field=models.CharField(max_length=32, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='anonymouscommentuser',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='anonymouscommentuser',
            name='token',
            field=models.CharField(max_length=128, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.TextField(blank=True, verbose_name='Avatar URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blinkie_url',
            field=models.TextField(blank=True, default='', verbose_name='Blinkie URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_public',
            field=models.BooleanField(default=False, verbose_name='Email Public'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
