# Generated by Django 4.0.6 on 2022-10-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcement",
            old_name="date",
            new_name="created_at",
        ),
    ]
