# Generated by Django 5.0.7 on 2024-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0004_alter_announcement_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="content_ja",
            field=models.TextField(blank=True),
        ),
    ]
