# Generated by Django 5.0.7 on 2024-12-15 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0005_announcement_content_ja"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="announcement",
            table="announcements_announcement",
        ),
    ]
