"""
Django settings for thatcomputerscientist project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# set n_connected_lc_users to 0 on startup
# import redis

# # r = redis.Redis(host='localhost', port=6379, db=0)
# r = redis.Redis(
#     host=os.getenv("REDIS_HOST"),
#     port=os.getenv("REDIS_PORT"),
#     password=os.getenv("REDIS_PASSWORD"),
#     db=0,
# )
# r.set("n_connected_lc_users", 0)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("AUTHORIZATION_STRING")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv("ENVIRONMENT") == "development" else False

ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = [
    "https://*.thatcomputerscientist.com",
    "http://*.thatcomputerscientist.com",
    "https://*.shi.foo",
    "http://localhost",
]
DOMAIN_NAME = "shi.foo"
SESSION_COOKIE_DOMAIN = (
    os.getenv("DOMAIN") if os.getenv("ENVIRONMENT") == "development" else ".shi.foo"
)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
ROOT_HOSTCONF = "thatcomputerscientist.hosts"
ROOT_URLCONF = "thatcomputerscientist.urls"
DEFAULT_HOST = "default"
LOGIN_URL = "/"

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.sessions",
    "django.contrib.sitemaps",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "channels",
    "storages",
    "thatcomputerscientist",
    "administration",
    "api",
    "authentication",
    "blog",
    "core",
    "services",
]

SITE_ID = 1
APPEND_SLASH = False

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "middleware.globalmetamiddleware.GlobalMetaMiddleware",
    "middleware.i18nmiddleware.I18NMiddleware",
    "middleware.userprofilemiddleware.UserProfileMiddleware",
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

AUTHENTICATION_BACKENDS = ["thatcomputerscientist.backends.CaseInsensitiveModelBackend"]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR / "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.letters.context_processors.unread_letter_count",
            ],
        },
    },
]

# WSGI_APPLICATION = 'thatcomputerscientist.wsgi.application'
ASGI_APPLICATION = "thatcomputerscientist.asgi.application"

_redis_password = os.getenv("REDIS_PASSWORD", "")
_redis_host = os.getenv("REDIS_HOST", "localhost")
_redis_port = os.getenv("REDIS_PORT", "6379")
_redis_url = (
    f"redis://:{_redis_password}@{_redis_host}:{_redis_port}"
    if _redis_password
    else f"redis://{_redis_host}:{_redis_port}"
)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [_redis_url],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, os.environ["DSN"]),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.getenv('REDIS_HOST')}:{os.getenv('REDIS_PORT')}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": os.getenv("REDIS_PASSWORD"),
        },
    }
}
from django.core.cache import cache

# clear the cache
for key in cache.keys("presence_*"):
    cache.delete(key)

SESSION_ENGINE = "django.contrib.sessions.backends.cache"

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = (("en", _("English")), ("ja", _("Japanese")))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"
# STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_USE_TLS = True
EMAIL_HOST = os.getenv("ORACLE_SMTP_HOST")
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD")

USERNAME_SMTP = os.getenv("ORACLE_SMTP_USER")
PASSWORD_SMTP = os.getenv("ORACLE_SMTP_PASSWORD")

# Celery Configuration
redis_password = os.getenv("REDIS_PASSWORD")
redis_host = os.getenv("REDIS_HOST")
redis_port = os.getenv("REDIS_PORT")

if redis_password:
    CELERY_BROKER_URL = f"redis://:{redis_password}@{redis_host}:{redis_port}/0"
    CELERY_RESULT_BACKEND = f"redis://:{redis_password}@{redis_host}:{redis_port}/0"
else:
    CELERY_BROKER_URL = f"redis://{redis_host}:{redis_port}/0"
    CELERY_RESULT_BACKEND = f"redis://{redis_host}:{redis_port}/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_BEAT_SCHEDULE = {
    "process-pending-and-spam-comments": {
        "task": "jobs.comments.process_pending_and_spam_comments",
        "schedule": 3600.0,
    },
    "delete-inactive-users": {
        "task": "jobs.users.delete_inactive_users",
        "schedule": 3600.0,
    },
    "refresh-steam-screenshots": {
        "task": "jobs.screenshots.refresh_steam_screenshots",
        "schedule": 6 * 3600.0,
    },
}

# Storage (CDN)
CDN_UPLOAD_ENDPOINT = os.getenv("CDN_UPLOAD_ENDPOINT")
CDN_ACCESS_ENDPOINT = os.getenv("CDN_ACCESS_ENDPOINT")
CDN_ACCESS_KEY = os.getenv("CDN_ACCESS_KEY")
CDN_SECRET_KEY = os.getenv("CDN_SECRET_KEY")
CDN_BUCKET = os.getenv("CDN_BUCKET")
CDN_USE_SSL = os.getenv("CDN_USE_SSL", "true").lower() == "true"

# Usernames
OWNER_USERNAME = os.getenv("OWNER_USERNAME")
MAL_USERNAME = os.getenv("MAL_USERNAME")

# Letters
LETTERS_MAX_LENGTH = 5000
LETTERS_INBOX_PER_PAGE = 20
LETTERS_BATCH_SIZE = 30
LETTERS_MAX_ATTACHMENTS = 8
LETTERS_MAX_ATTACHMENT_SIZE = 32 * 1024 * 1024
