from django.utils.translation import gettext_lazy as _

MODE_CHOICES = [
    ("default", _("Default")),
    ("book", _("Book")),
    ("light_novel", _("Light Novel")),
    ("short_stories", _("Short Stories")),
    ("diary", _("Diary")),
    ("poetry", _("Poetry")),
]

STATUS_CHOICES = [
    ("ongoing", _("Ongoing")),
    ("completed", _("Completed")),
    ("hiatus", _("Hiatus")),
]

GENRE_CHOICES = [
    ("fantasy", _("Fantasy")),
    ("sci_fi", _("Sci-Fi")),
    ("romance", _("Romance")),
    ("horror", _("Horror")),
    ("mystery", _("Mystery")),
    ("thriller", _("Thriller")),
    ("comedy", _("Comedy")),
    ("drama", _("Drama")),
    ("slice_of_life", _("Slice of Life")),
    ("action", _("Action")),
    ("adventure", _("Adventure")),
    ("historical", _("Historical")),
    ("isekai", _("Isekai")),
    ("mecha", _("Mecha")),
    ("supernatural", _("Supernatural")),
    ("psychological", _("Psychological")),
    ("tragedy", _("Tragedy")),
    ("ecchi", _("Ecchi")),
    ("harem", _("Harem")),
    ("mahou_shoujo", _("Mahou Shoujo")),
    ("cyberpunk", _("Cyberpunk")),
    ("dystopian", _("Dystopian")),
    ("noir", _("Noir")),
    ("satire", _("Satire")),
]

TONE_CHOICES = [
    ("dark", _("Dark")),
    ("light", _("Light")),
    ("comedic", _("Comedic")),
    ("serious", _("Serious")),
    ("melancholic", _("Melancholic")),
    ("whimsical", _("Whimsical")),
    ("gritty", _("Gritty")),
    ("surreal", _("Surreal")),
    ("wholesome", _("Wholesome")),
    ("bittersweet", _("Bittersweet")),
    ("absurdist", _("Absurdist")),
    ("noir", _("Noir")),
    ("dreamy", _("Dreamy")),
    ("tense", _("Tense")),
]

FORM_CHOICES = [
    ("free_verse", _("Free Verse")),
    ("haiku", _("Haiku")),
    ("tanka", _("Tanka")),
    ("sonnet", _("Sonnet")),
    ("limerick", _("Limerick")),
    ("ballad", _("Ballad")),
    ("ode", _("Ode")),
    ("elegy", _("Elegy")),
    ("ghazal", _("Ghazal")),
    ("villanelle", _("Villanelle")),
    ("acrostic", _("Acrostic")),
    ("prose_poetry", _("Prose Poetry")),
    ("concrete", _("Concrete")),
    ("renga", _("Renga")),
    ("spoken_word", _("Spoken Word")),
]

MOOD_CHOICES = [
    ("happy", _("Happy")),
    ("sad", _("Sad")),
    ("anxious", _("Anxious")),
    ("calm", _("Calm")),
    ("angry", _("Angry")),
    ("grateful", _("Grateful")),
    ("tired", _("Tired")),
    ("excited", _("Excited")),
    ("reflective", _("Reflective")),
    ("nostalgic", _("Nostalgic")),
    ("hopeful", _("Hopeful")),
    ("stressed", _("Stressed")),
    ("content", _("Content")),
    ("lonely", _("Lonely")),
    ("inspired", _("Inspired")),
    ("melancholic", _("Melancholic")),
    ("peaceful", _("Peaceful")),
    ("frustrated", _("Frustrated")),
    ("numb", _("Numb")),
    ("curious", _("Curious")),
]

RESERVED_JOURNAL_SLUGS = [
    "new",
    "news",
    "create",
    "view",
    "read",
    "edit",
    "delete",
    "settings",
    "config",
    "configuration",
    "all",
    "my",
    "mine",
    "public",
    "private",
    "shared",
    "favorites",
    "favorite",
    "drafts",
    "tags",
    "tag",
    "search",
    "archive",
    "about",
    "privacy",
    "terms",
    "contact",
    "help",
    "support",
    "login",
    "logout",
    "signup",
    "register",
    "signin",
    "signout",
    "user",
    "users",
    "profile",
    "admin",
    "administrator",
    "dashboard",
    "api",
    "static",
    "media",
    "assets",
    "journal",
    "journals",
    "blog",
    "blogs",
    "post",
    "posts",
    "entry",
    "entries",
    "index",
    "home",
    "root",
    "www",
    "mail",
    "email",
    "ftp",
    "ssh",
    "ssl",
    "secure",
    "feed",
    "rss",
    "atom",
    "xml",
    "json",
    "css",
    "js",
    "javascript",
    "img",
    "image",
    "images",
    "file",
    "files",
    "upload",
    "download",
    "cache",
    "tmp",
    "temp",
    "log",
    "logs",
    "backup",
    "db",
    "database",
    "test",
    "testing",
    "dev",
    "development",
    "prod",
    "production",
    "staging",
    "journal-of-random-thoughts",
]

RESERVED_JOURNAL_NAMES = [
    "journal",
    "journal of random thoughts",
    "my journal",
    "personal journal",
    "diary",
    "blog",
    "weblog",
    "notes",
    "thoughts",
    "admin",
    "administrator",
    "test",
    "sample",
    "demo",
    "example",
]
