# Generated by Django 5.1.4 on 2024-12-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="slug",
            field=models.SlugField(default="", max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
