name: Deploy
on: [push]
jobs:
  deploy:
    name: Deploy App
    runs-on: "self-hosted"
    steps:
      - uses: actions/checkout@v2
      - name: Run Script
        working-directory: _work
        run: sh /home/ubuntu/deploy.sh
