name: Deploy
on: [push]
jobs:
  deploy:
    name: Deploy App
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Switch to thatcomputerscientist folder
        run: cd /home/ubuntu/thatcomputerscientist/thatcomputerscientist/thatcomputerscientist
      - name: Install Requirements
        run: pip3 install -r requirements.txt
      - name: Run Django Migrations
        run: python3 manage.py migrate
      - name: Run Django Makemigrations
        run: python3 manage.py makemigrations
      - name: Run Django Collectstatic
        run: python3 manage.py collectstatic --noinput
      - name: Kill Gunicorn
        run: pkill gunicorn
      - name: Start Gunicorn
        run: gunicorn --bind :8000 --workers 3 thatcomputerscientist.wsgi --daemon
